buildCommand: |
  apt-get update && apt-get install -y curl unzip wget gnupg ca-certificates fonts-liberation xdg-utils && \
  pip install -r requirements.txt && \
  bash render-build.sh

startCommand: ""

services:
  - type: cron
    name: start-shift
    schedule: "0 0 1-7 * *"
    command: "python app.py --mode start"

  - type: cron
    name: end-shift
    schedule: "0 5 1-7 * *"
    command: "python app.py --mode end"
